import { Card, CardContent, CardHeader, CardTitle, Tabs, TabsContent, TabsList, TabsTrigger } from '@zproo/ui';
import { BusFront, FileText, ShieldCheck } from 'lucide-react';
import type { BusTripOffer } from '@zproo/types';

export function BusInfoPanel({ trip }: { trip: BusTripOffer }) {
  const policies = [
    ['Child travel', 'Children must travel with a responsible adult and carry any required identification. Operator-specific age rules apply.'],
    ['Luggage', 'Carry only the luggage allowance shown by the operator. Keep valuables and documents with you.'],
    ['Pet policy', 'Pets are allowed only when the operator explicitly permits them and may require a carrier or prior approval.'],
    ['Liquor / alcohol', 'Alcohol carriage or consumption is subject to operator rules and applicable law. Do not board while intoxicated.'],
    ['Pick-up time', 'Reach the boarding point at least 15 minutes before the scheduled departure.'],
    ['Cancellation', trip.cancellationPolicy.map((r) => r.hoursBefore > 0 ? `${r.refundPercent}% refund when cancelled more than ${r.hoursBefore}h before departure` : 'No refund after the final cutoff').join('; ')],
  ];
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><BusFront className="size-5 text-primary" /> Bus information & policies</CardTitle></CardHeader><CardContent><Tabs defaultValue="route"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="route">Route</TabsTrigger><TabsTrigger value="stops">Rest stops</TabsTrigger><TabsTrigger value="safety">Safety</TabsTrigger><TabsTrigger value="fitness">Fitness</TabsTrigger><TabsTrigger value="insurance">Insurance</TabsTrigger><TabsTrigger value="policies">Policies</TabsTrigger></TabsList><TabsContent value="route" className="pt-4 text-sm"><p className="font-bold">{trip.from.name} → {trip.to.name}</p><p className="mt-1 text-muted">{trip.operator.name} · {trip.bus.name} · {trip.distanceKm} km</p></TabsContent><TabsContent value="stops" className="pt-4 text-sm"><p>Rest stops are operator-scheduled and may change with traffic or operational needs. Ask the crew before leaving the coach.</p></TabsContent><TabsContent value="safety" className="pt-4 text-sm"><p className="flex gap-2"><ShieldCheck className="size-5 shrink-0 text-success" />Follow crew instructions, remain seated while moving, and keep aisles clear.</p></TabsContent><TabsContent value="fitness" className="pt-4 text-sm"><p>The selected coach is supplied through the operator/provider inventory. Vehicle fitness and maintenance are the operator's responsibility.</p></TabsContent><TabsContent value="insurance" className="pt-4 text-sm"><p>Insurance coverage, where provided, follows the operator/provider terms attached to the trip. Review the booking terms before payment.</p></TabsContent><TabsContent value="policies" className="pt-4"><div className="grid gap-3 sm:grid-cols-2">{policies.map(([title, text]) => <div key={title} className="rounded-xl border border-border p-3"><p className="flex items-center gap-2 font-semibold"><FileText className="size-4 text-primary" />{title}</p><p className="mt-1 text-sm text-muted">{text}</p></div>)}</div></TabsContent></Tabs></CardContent></Card>;
}
