export type Block =
  | { t: "h"; text: string }
  | { t: "p"; text: string }
  | { t: "list"; items: string[] }
  | { t: "tip"; text: string };

export interface Post {
  slug: string;
  title: string;
  excerpt: string;
  category: Category;
  image: string;
  imageAlt: string;
  date: string;
  mins: number;
  author: string;
  body: Block[];
}

export const CATEGORIES = ["All", "Destinations", "Bus travel", "Rail tips", "Stays", "Travel hacks"] as const;
export type Category = Exclude<(typeof CATEGORIES)[number], "All">;

export const POSTS: Post[] = [
  {
    slug: "goa-beyond-the-beaches",
    title: "Goa beyond the beaches: a slower, smarter 4-day plan",
    excerpt: "Skip the crowded shacks. Here is how to see old Goa, spice farms and quiet coves without rushing.",
    category: "Destinations",
    image: "/assets/blog/scene-beach.svg",
    imageAlt: "Beach in Goa with palm trees",
    date: "27 Sep 2026",
    mins: 7,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Most first-time visitors treat Goa as one long beach day. It rewards people who slow down. Split the state into North and South, pick one base for each half, and let the days breathe." },
      { t: "h", text: "Day 1–2: North Goa, but earlier" },
      { t: "p", text: "Reach popular spots before 9 am and you get empty sand, cooler air and better photos. Spend the afternoon in Fontainhas and old Panjim, where Portuguese-era lanes and small cafés are best explored on foot." },
      { t: "h", text: "Day 3: Old Goa and a spice farm" },
      { t: "p", text: "The churches of Old Goa are quiet and beautiful in the morning. Pair them with a spice plantation lunch in the hinterland for a very different side of the state." },
      { t: "h", text: "Day 4: South Goa calm" },
      { t: "p", text: "Palolem, Agonda and Butterfly Beach are gentler, greener and less crowded. Book a stay here if you want to actually rest." },
      { t: "list", items: ["Best months: November to February", "Rent a scooter only if you are confident on local roads", "Book overnight buses early for weekends and long holidays"] },
      { t: "tip", text: "Travelling from Pune or Mumbai? An overnight sleeper bus saves a hotel night and puts you in Goa by morning." },
    ],
  },
  {
    slug: "choose-the-right-bus-seat",
    title: "How to choose the right bus seat (and avoid the bad ones)",
    excerpt: "Window or aisle, upper or lower berth, front or back. A quick guide to picking the seat that suits your trip.",
    category: "Bus travel",
    image: "/assets/blog/scene-bus.svg",
    imageAlt: "Intercity coach on a highway",
    date: "24 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "A good seat can turn an overnight journey from tiring to comfortable. The best choice depends on the bus type, the road and how you like to travel." },
      { t: "h", text: "Seater buses" },
      { t: "p", text: "Seats near the middle of the bus feel the smoothest. The last rows bounce more on uneven roads, while the front gives the best view but more braking movement." },
      { t: "h", text: "Sleeper buses" },
      { t: "p", text: "Lower berths are easier to get in and out of and suit families and older travellers. Upper berths feel more private but sway more, and the ride over the rear wheels can be bumpy." },
      { t: "list", items: ["Light sleepers: choose lower berths near the front", "Motion sickness: sit near the middle, by a window", "Charging: check the amenities list before you pay", "Solo travellers: pick seats marked for ladies if you prefer"] },
      { t: "tip", text: "Open the seat map before paying. Real layouts make it easy to avoid seats next to the door or the last row." },
    ],
  },
  {
    slug: "pnr-status-explained",
    title: "CNF, RAC, WL: what your PNR status really means",
    excerpt: "A plain-language decoder for railway booking codes, plus what to do while you are still waitlisted.",
    category: "Rail tips",
    image: "/assets/blog/scene-train.svg",
    imageAlt: "Train passing through green countryside",
    date: "21 Sep 2026",
    mins: 6,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Railway statuses look cryptic until you know the basics. Once you do, planning a journey gets much less stressful." },
      { t: "list", items: ["CNF: confirmed. You have a berth or seat.", "RAC: reservation against cancellation. You can travel and share a berth until a full berth frees up.", "WL: waitlisted. You move up as others cancel, and may be confirmed before departure.", "GNWL and RLWL: waitlist types that differ by quota and origin"] },
      { t: "h", text: "What to do when you are waitlisted" },
      { t: "p", text: "Check the status again the day before travel and after the chart is prepared. If you are still waitlisted on the final chart, the ticket is generally cancelled and refunded automatically." },
      { t: "tip", text: "Always keep a backup, like a bus booking or a flexible plan, for time-sensitive trips when you are on a long waitlist." },
    ],
  },
  {
    slug: "hotel-booking-checklist",
    title: "The 8-point hotel booking checklist we use ourselves",
    excerpt: "Before you tap Pay, run through these checks so your stay has no unpleasant surprises.",
    category: "Stays",
    image: "/assets/blog/scene-hotel.svg",
    imageAlt: "Lake palace hotel in Udaipur",
    date: "18 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "A cheap room is not a good deal if it is far from where you need to be or charges for everything. Use this checklist before you confirm." },
      { t: "list", items: ["Total price including taxes and fees", "Cancellation policy and free-cancellation deadline", "Check-in and check-out times", "Distance to your station, airport or venue", "Recent guest ratings, not only the average", "Breakfast, Wi-Fi and parking inclusions", "Couple, family or group policy", "Photos of the actual room type you are booking"] },
      { t: "tip", text: "Arriving late at night? Message the property in advance so your room is held and check-in is quick." },
    ],
  },
  {
    slug: "manali-in-monsoon-and-winter",
    title: "Manali in monsoon vs winter: which season is right for you?",
    excerpt: "Green valleys or snow-capped peaks? We compare weather, roads, costs and crowds.",
    category: "Destinations",
    image: "/assets/blog/scene-mountain.svg",
    imageAlt: "Snow-capped mountains around Manali",
    date: "14 Sep 2026",
    mins: 6,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Manali changes completely with the seasons, and the best time depends on what you want from the trip." },
      { t: "h", text: "Monsoon (July–September)" },
      { t: "p", text: "Lush green valleys, fewer tourists and lower hotel rates. The trade-off is landslide risk and slower roads, so leave extra buffer time." },
      { t: "h", text: "Winter (December–February)" },
      { t: "p", text: "Snow, cosy stays and bonfires. It is also cold and busy around holidays, so book buses and rooms early." },
      { t: "list", items: ["Pack layers whatever the season", "Check road conditions before leaving", "Carry some cash for remote areas", "Take an overnight bus to save daylight for sightseeing"] },
    ],
  },
  {
    slug: "pack-light-travel-faster",
    title: "Pack light, travel faster: a carry-on packing method that works",
    excerpt: "One bag, no stress. A simple system for weekends, work trips and week-long holidays.",
    category: "Travel hacks",
    image: "/assets/blog/scene-plane.svg",
    imageAlt: "Aeroplane taking off",
    date: "10 Sep 2026",
    mins: 4,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Checking a bag costs time and money. With a little planning, most trips fit in one carry-on." },
      { t: "list", items: ["Choose one colour palette so everything matches", "Roll clothes and use packing cubes", "Wear your bulkiest shoes and jacket while travelling", "Decant toiletries into small bottles", "Keep documents, charger and a power bank in an easy-to-reach pocket"] },
      { t: "tip", text: "Lay everything out on your bed, then put one third back. You will almost never miss it." },
    ],
  },
  {
    slug: "kerala-backwaters-guide",
    title: "Kerala backwaters: houseboat or homestay?",
    excerpt: "Two great ways to see Alleppey and Kumarakom. Here is how to choose, and what each really costs.",
    category: "Stays",
    image: "/assets/blog/scene-backwater.svg",
    imageAlt: "Backwater resort in Kerala",
    date: "06 Sep 2026",
    mins: 6,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "A houseboat is an experience. A homestay is a connection. Both work well, and the right one depends on your group and your pace." },
      { t: "h", text: "Houseboat" },
      { t: "p", text: "Great for a single memorable night with meals cooked on board. Book a smaller boat for a quieter, cheaper trip and confirm what is included." },
      { t: "h", text: "Homestay" },
      { t: "p", text: "Often better value. You get local food, village walks and canoe rides, and you can stay for several nights." },
      { t: "tip", text: "Combine both: one homestay night, then a sunset houseboat cruise." },
    ],
  },
  {
    slug: "save-money-on-every-trip",
    title: "7 practical ways to save money on every trip",
    excerpt: "No gimmicks. Just timing, flexibility and a few habits that keep your travel budget under control.",
    category: "Travel hacks",
    image: "/assets/blog/scene-tips.svg",
    imageAlt: "Desert fort in Rajasthan",
    date: "02 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Saving on travel is mostly about planning, not sacrificing comfort." },
      { t: "list", items: ["Book early for festivals and long weekends", "Travel mid-week when fares are lower", "Compare bus, train and flight for the same route", "Be flexible by a day or two on dates", "Use free-cancellation stays while you plan", "Pay attention to total price, not just the headline fare", "Check wallet offers and coupons before paying"] },
      { t: "tip", text: "Set a small daily budget for food and local transport. It makes the trip easier to enjoy." },
    ],
  },
  {
    slug: "mumbai-in-48-hours",
    title: "Mumbai in 48 hours: what to see, eat and skip",
    excerpt: "Marine Drive sunsets, local trains and vada pav. A tight, realistic weekend plan for India's busiest city.",
    category: "Destinations",
    image: "/assets/blog/scene-city.svg",
    imageAlt: "Mumbai skyline at dusk",
    date: "29 Sep 2026",
    mins: 7,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Mumbai rewards short, well-planned visits. Cluster your days by area so you spend time exploring instead of sitting in traffic." },
      { t: "h", text: "Day 1: South Mumbai" },
      { t: "p", text: "Start at the Gateway of India, walk through Colaba's lanes, then head to a classic Irani café for breakfast. Spend the afternoon around Kala Ghoda's galleries and finish with sunset on Marine Drive." },
      { t: "h", text: "Day 2: Bandra and beyond" },
      { t: "p", text: "Explore Bandra's street art, Carter Road and Bandstand. Save the evening for a proper seafood dinner and a slow walk by the sea." },
      { t: "list", items: ["Use local trains outside peak hours (9–11 am and 6–8 pm)", "Keep small change for autos and street food", "Skip the tourist restaurants near major landmarks", "Carry a light rain jacket from June to September"] },
      { t: "tip", text: "Coming from Pune? Early-morning buses and trains reach Mumbai before the city fully wakes up, which gives you a full first day." },
    ],
  },
  {
    slug: "kashmir-first-timer-guide",
    title: "Kashmir for first-timers: a calm 6-day route",
    excerpt: "Dal Lake shikaras, Gulmarg's meadows and Pahalgam's rivers, arranged so you are never rushing between valleys.",
    category: "Destinations",
    image: "/assets/blog/scene-lake.svg",
    imageAlt: "Lake and snow-capped mountains in Kashmir",
    date: "26 Sep 2026",
    mins: 8,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Kashmir is best travelled slowly. Three bases, two nights each, is a comfortable rhythm." },
      { t: "h", text: "Srinagar (2 nights)" },
      { t: "p", text: "Take a shikara ride on Dal Lake at sunrise, wander the Mughal gardens and try a traditional wazwan meal." },
      { t: "h", text: "Gulmarg (2 nights)" },
      { t: "p", text: "Ride the gondola for mountain views, walk the meadows in summer or try beginner skiing in winter." },
      { t: "h", text: "Pahalgam (2 nights)" },
      { t: "p", text: "Riverside walks, pony rides to Baisaran and quiet evenings. This is the place to slow down." },
      { t: "list", items: ["Best months: April to June and September to October", "Carry warm layers even in summer", "Book flights and stays early for peak season", "Check local advisories before you travel"] },
    ],
  },
  {
    slug: "overnight-bus-survival-kit",
    title: "The overnight bus survival kit: what to pack and how to sleep",
    excerpt: "A small bag of the right things can make a night journey feel almost restful.",
    category: "Bus travel",
    image: "/assets/blog/scene-bus.svg",
    imageAlt: "Bus travelling on a highway at dusk",
    date: "23 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Night buses are efficient and affordable, but comfort takes preparation. Keep the essentials in a small bag you can reach without opening your luggage." },
      { t: "list", items: ["Neck pillow and a light blanket or shawl", "Eye mask and earplugs", "Power bank and a short charging cable", "Water bottle and light snacks", "Wet wipes, tissues and a small sanitiser", "Photo ID and a printed or saved e-ticket"] },
      { t: "h", text: "Sleeping better" },
      { t: "p", text: "Eat lightly before boarding, use the restroom during the last stop, and put your phone on silent. Keep valuables in a zipped pocket." },
      { t: "tip", text: "Confirm the boarding point and reporting time the evening before. Arriving 15 minutes early avoids the usual last-minute rush." },
    ],
  },
  {
    slug: "long-train-journey-comfort-guide",
    title: "Long train journeys: food, comfort and staying charged",
    excerpt: "From choosing a berth to packing meals that stay fresh, a practical guide to 12-hour-plus rail travel.",
    category: "Rail tips",
    image: "/assets/blog/scene-train.svg",
    imageAlt: "Train travelling through green countryside",
    date: "20 Sep 2026",
    mins: 6,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Rail is one of the most comfortable ways to cover long distances. A few habits make it even better." },
      { t: "h", text: "Choose the right class" },
      { t: "p", text: "Sleeper is budget-friendly, 3A adds air-conditioning and privacy, while 2A and 1A offer more space. For overnight trips, AC classes are usually worth it." },
      { t: "h", text: "Food and water" },
      { t: "list", items: ["Pack dry snacks, fruit and simple meals in sealed boxes", "Carry a refillable bottle and top up at major stations", "Avoid oily food if you get motion sickness", "Keep small change for tea and snacks"] },
      { t: "tip", text: "Lower berths suit older travellers and families. Upper berths give more privacy for solo travellers." },
    ],
  },
  {
    slug: "rajasthan-forts-and-palaces-route",
    title: "Rajasthan's forts and palaces: a 7-day route that makes sense",
    excerpt: "Jaipur, Jodhpur, Jaisalmer and Udaipur without doubling back. Distances, timings and how to travel between them.",
    category: "Destinations",
    image: "/assets/blog/scene-desert.svg",
    imageAlt: "Desert fort in Rajasthan at sunset",
    date: "16 Sep 2026",
    mins: 8,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Rajasthan is large, and the best routes flow in one direction. This loop keeps travel days short and sightseeing days full." },
      { t: "list", items: ["Jaipur (2 nights): Amber Fort, City Palace, old bazaars", "Jodhpur (1 night): Mehrangarh Fort and the blue lanes", "Jaisalmer (2 nights): golden fort and a desert sunset", "Udaipur (2 nights): lakes, palaces and rooftop dinners"] },
      { t: "h", text: "Getting around" },
      { t: "p", text: "Overnight buses and trains connect most of these cities. Use the night journeys to save hotel costs and keep your days free." },
      { t: "tip", text: "Visit between October and March. Summer heat can make forts uncomfortable in the afternoon." },
    ],
  },
  {
    slug: "weekend-getaways-from-pune",
    title: "8 weekend getaways from Pune within 4 hours",
    excerpt: "Hill stations, forts and lakeside stays that fit neatly into a Friday-night to Sunday-evening plan.",
    category: "Destinations",
    image: "/assets/blog/scene-hills.svg",
    imageAlt: "Winding road through green hills",
    date: "12 Sep 2026",
    mins: 6,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Pune's location makes it a great base for quick escapes. These are easy to reach by road or bus and work well over a weekend." },
      { t: "list", items: ["Lonavala and Khandala: monsoon waterfalls and viewpoints", "Mahabaleshwar: strawberries, viewpoints and cool evenings", "Panchgani: quiet, table-land views", "Alibaug: beaches and forts a short ferry ride from Mumbai", "Bhandardara: lakes, waterfalls and star-filled nights", "Matheran: a car-free hill station", "Kaas Plateau: wildflowers, seasonally", "Tamhini Ghat: monsoon drives and streams"] },
      { t: "tip", text: "Leave early on Saturday and return late on Sunday to avoid the worst of the weekend traffic." },
    ],
  },
  {
    slug: "how-refunds-work",
    title: "How cancellations and refunds actually work",
    excerpt: "What affects your refund amount, how long it takes and what to keep handy if it is delayed.",
    category: "Travel hacks",
    image: "/assets/blog/scene-tips.svg",
    imageAlt: "Suitcase with a ticket and coin",
    date: "08 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Refund rules depend on the operator, ticket type and how close you are to departure. Understanding them helps you cancel at the right time." },
      { t: "h", text: "What affects your refund" },
      { t: "list", items: ["How early you cancel before departure", "The operator's or airline's cancellation policy", "Non-refundable fares and convenience fees", "Payment method and bank processing time"] },
      { t: "h", text: "If your refund is delayed" },
      { t: "p", text: "Refunds usually return to your original payment method. Banks can take several working days, so wait for the stated period before following up." },
      { t: "tip", text: "Save your booking ID and payment reference. They make any follow-up much faster." },
    ],
  },
  {
    slug: "solo-travel-safety-basics",
    title: "Solo travel safety basics that don't spoil the fun",
    excerpt: "Simple, sensible habits for staying safe and confident when you are travelling on your own.",
    category: "Travel hacks",
    image: "/assets/blog/scene-city.svg",
    imageAlt: "City skyline at night",
    date: "04 Sep 2026",
    mins: 5,
    author: "ZPROO GO Editorial",
    body: [
      { t: "p", text: "Travelling alone can be freeing and rewarding. Good preparation lets you relax and enjoy it." },
      { t: "list", items: ["Share your itinerary and live location with someone you trust", "Book arrivals in daylight where possible", "Read recent reviews for stays before booking", "Keep copies of your ID and tickets on your phone", "Trust your instincts and leave any situation that feels off", "Save local emergency numbers and your stay's address offline"] },
      { t: "tip", text: "Choose well-reviewed, well-located stays for your first night in a new city. It sets the tone for the whole trip." },
    ],
  },
];
